# Generated by Django 5.2.16 on 2026-09-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='role', to='rbac.permissions'),
        ),
    ]
