# Generated by Django 5.2.16 on 2026-09-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_role_permissions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permissions',
            new_name='Permission',
        ),
    ]
