# Generated by Django 5.2.16

from django.db import migrations


def create_user_permissions(apps, schema_editor):
    Permission = apps.get_model("rbac", "Permission")

    permissions = [
        {
            "name": "View Users",
            "codename": "user_view",
            "description": "Can view users.",
        },
        {
            "name": "Create Users",
            "codename": "user_create",
            "description": "Can create users.",
        },
        {
            "name": "Update Users",
            "codename": "user_update",
            "description": "Can update users.",
        },
        {
            "name": "Delete Users",
            "codename": "user_delete",
            "description": "Can delete users.",
        },
    ]

    for permission in permissions:
        Permission.objects.get_or_create(
            codename=permission["codename"],
            defaults=permission,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0004_rename_permissions_permission"),
    ]

    operations = [
        migrations.RunPython(create_user_permissions),
    ]